### ISSUE TITLE
When I ran the train.py file, I encountered a problem, I hope you can answer it. Thank you.

### ISSUE THREAD

**Issue by wry980105** [HanHan55/Graph2plan#7]
File "train.py", line 604, in <module>
    main(args)
  File "train.py", line 473, in main
    trainer.run(train_loader,max_epochs=args.epoch)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 446, in run
    self._handle_exception(e)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 433, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 399, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 387, in _run_once_on_dataset
    for batch in self.state.dataloader:
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhaoliuqing/wry/Graph2plan-master/Network/model/floorplan.py", line 223, in __getitem__
    return fp.get_train_data()
  File "/home/zhaoliuqing/wry/Graph2plan-master/Network/model/floorplan.py", line 202, in get_train_data
    boxes = self.get_boxes(tensor=tensor)
  File "/home/zhaoliuqing/wry/Graph2plan-master/Network/model/floorplan.py", line 159, in get_boxes
    boxes = np.apply_along_axis(norm,1,boxes)
  File "/home/zhaoliuqing/anaconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 380, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/home/zhaoliuqing/wry/Graph2plan-master/Network/model/floorplan.py", line 158, in <lambda>
    norm = lambda box:np.array([X[box[1]],Y[box[0]],X[box[3]-1],Y[box[2]-1]])
IndexError: index 208 is out of bounds for axis 0 with size 208

**Comment by zzilch** [comment]
Can you provide the name of the error data item? You can print it at [here](https://github.com/HanHan55/Graph2plan/blob/dd082cb98905f85ecf1fd0589927076f61940662/Network/model/floorplan.py#L193)

**Comment by wry980105** [comment]
Thank you for your reply! 
It is this mistake that has occurred：“norm = lambda box:np.array([X[box[1]],Y[box[0]],X[box[3]-1],Y[box[2]-1]])
IndexError: index 208 is out of bounds for axis 0 with size 208”.I read the data_item，it maybe the gtBoxNew has problem.But i am not sure and don't know how to handle it.Could you please give me some methods?

**Comment by zzilch** [comment]
Yeah, I think there is something wrong with the training data. I need you to print the name of the wrong data.
In the class `FloorPlanDataset` , it will call `get_train_data` to get the traininng data of a `Floorplan`.
And in `get_train_data`, it will call `get_boxes` which casued the error you encountered.
You can print the name before it calls `get_boxes` in the line 193 of `floorplan.py`.
If you provide the name of the problem data, I can figure out what happened.

**Comment by wry980105** [comment]
I print the data.name as you said.








The data that went wrong was this one up here










The box name that went wrong was this one up here.







But I ran it the second time and&nbsp; this data was wrong.



Each time I ran it,&nbsp; the&nbsp;wrong&nbsp;data was different.



It's so stange that I don't know what is wrong.










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HanHan55/Graph2plan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月18日(星期天) 凌晨0:13
收件人:&nbsp;"HanHan55/Graph2plan"<Graph2plan@noreply.github.com&gt;;
抄送:&nbsp;"瑩*瑩"<1151735452@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [HanHan55/Graph2plan] When I ran the train.py file, I encountered a problem, I hope you can answer it. Thank you. (#7)





 
Yeah, I think there is something wrong with the training data. I need you to print the name of the wrong data.
 In the class FloorPlanDataset , it will call get_train_data to get the traininng data of a Floorplan.
 And in get_train_data, it will call get_boxes which casued the error you encountered.
 You can print the name before it calls get_boxes in the line 193 of floorplan.py.
 If you provide the name of the problem data, I can figure out what happened.

**Comment by zzilch** [comment]
Sorry, did you paste any images? I cannot see anyone of them.

**Comment by wry980105** [comment]
I print the data.name as you said.
“&nbsp; &nbsp; &nbsp; &nbsp;def get_train_data(self, tensor=True):
&nbsp; &nbsp; &nbsp; &nbsp; name = self.data.name
&nbsp; &nbsp; &nbsp; &nbsp; print("____________________")
&nbsp; &nbsp; &nbsp; &nbsp; print(name)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;”


“&nbsp;17678
____________________"
The data that went wrong was this one up here”


“tensor([[0.8256, 0.7801, 0.3333, 0.4277],
&nbsp; &nbsp; &nbsp; &nbsp; [0.8953, 0.4608, 0.1938, 0.1988],
&nbsp; &nbsp; &nbsp; &nbsp; [0.8140, 0.2199, 0.3566, 0.2711],
&nbsp; &nbsp; &nbsp; &nbsp; [0.0930, 0.2861, 0.1705, 0.2590],
&nbsp; &nbsp; &nbsp; &nbsp; [0.4264, 0.3404, 0.7132, 0.6807]])”



The box name that went wrong was this one up here.


"44257
____________________"
“3744
_________________”




But I ran it the second time and&nbsp; this data was wrong.



Each time I ran it,&nbsp; the&nbsp;wrong&nbsp;data was different.



It's so stange that I don't know what is wrong.




In addition，may&nbsp;I&nbsp;ask&nbsp;if we can add a WeChat?We can talk conveniently.My number is 13750854386,thank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HanHan55/Graph2plan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 上午8:23
收件人:&nbsp;"HanHan55/Graph2plan"<Graph2plan@noreply.github.com&gt;;
抄送:&nbsp;"瑩*瑩"<1151735452@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [HanHan55/Graph2plan] When I ran the train.py file, I encountered a problem, I hope you can answer it. Thank you. (#7)





 
Sorry, did you paste any images? I cannot see anyone of them.

**Comment by LucaJeevanjee** [comment]
Hello, I am receiving this issue as well,
The index in which the error occurs changes when the batch size and number of workers is changed.

![image](https://user-images.githubusercontent.com/30826343/134963833-c000b80f-2f61-4251-a959-5df9ace11d31.png)

This is the log from when it crashes.
Looks like either training data: 27184 or 75591
Thanks in advance!
