### ISSUE TITLE
problems about the interface

### ISSUE THREAD

**Issue by JiaqiuZhou** [HanHan55/Graph2plan#8]
Internal Server Error: /index/NumSearch/
Traceback (most recent call last):
  File "/home/.../anaconda3/envs/g2p_app/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/.../anaconda3/envs/g2p_app/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/.../Code/Graph2plan/Interface/Houseweb/views.py", line 148, in NumSearch
    testName = data_new[0].split(".")[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by cihankaradogan** [comment]
Could you solve it?

**Comment by JiaqiuZhou** [comment]
I forgot how I solve it. Maybe the data input is wrong.

**Comment by SuroshAhmadZobair** [comment]
any updates?
